GET http://localhost:8081/users/listemailsids
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZDU3OWE3YTEyY2VmNjU5NGEwZTEyMCIsImVtYWlsIjoiYm9zc0BmcmVlLmZyIiwiaWF0IjoxNTc0MjcyODA3LCJleHAiOjE1NzQyNzQ2MDd9.7eiCmYxWYJKUPlz8JE2Gdw15W-6-fJHIg_2kIZU9jOc


