GET http://localhost:8081/users/list
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZDU3OWE3YTEyY2VmNjU5NGEwZTEyMCIsImVtYWlsIjoiYm9zc0BmcmVlLmZyIiwiaWF0IjoxNTc0MzIyNjMwLCJleHAiOjE1NzQzMjQ0MzB9.f1bA9-W6IJ50CEdSg_mJ9WYiULhB5xpIjcWyhG9HdJU


