POST http://localhost:8081/users/register HTTP/1.1
content-type: application/json

{
    "name": "Boss swansea",
    "email": "boss@free.fr",
    "password": "manager",
    "description": "This is me"
}
